### ISSUE TITLE
Accessibility - Too Small of Text

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#1]
The text on the Samsung – Galaxy Tab S – version 5.0.2 it is too small. I’m afraid when people look at the application on a phone the text will look even smaller and people won’t be able to read it.

**Comment by aquilent-dgemoets** [comment]
Sweat & Toil is not optimized for tablets.  Custom tablet work is out of scope, just like in iOS.
That said, we may be able to specify larger font sizes for larger screens, as time permits.  This is currently at the top of our "if time permits" list.

**Comment by MikePulsiferDOL** [comment]
John's concern is that if the text is small on a tablet, it'll likely be very small on a phone.  Can you please respond to this concern?

**Comment by aquilent-dgemoets** [comment]
I believe the opposite to be the case.  On an iOS tablet, the UI of a phone app is scaled up to tablet dimensions.  So something small on a tablet would be very small on a phone.  In Android, the system handles most of the work to adjust each application's user interface to the screen on which it is displayed, but does not simply scale the UI.  So the font size you see on the tablet is the same size as what you'll see on a phone.  The platform supports mechanisms to set larger font sizes on larger devices-- exploring this is the top of "if time permits" list.

**Comment by jfc3-dol** [comment]
I understand 'Sweat & Toil' is a phone application, but I only have an Android tablet  to do my testing with. 

Is there someone on your team or in ILAB that has an Android phone I could check these issue on to make sure these and other issues are not caused because I'm using a Galaxy tablet?

**Comment by jfc3-dol** [comment]
After being concerned that the text and images (flags, etc.) of the new ILAB 'Sweat & Toil' Android application would be too small after seeing it on the 'Galaxy Tab S' tablet. On Friday, November 20, 2015, I looked at an 'LG Tribute 2' phone and the images looked fine. 

Because of these findings I'm closing this and other related issues.
