### ISSUE TITLE
Usability - Individual Country Screen - PDF Naming Convention Differs between iOS and Android

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#10]
Why is the PDF tab in the Android application called “Full Report” and on the iPad called “Report PDF”? Doing this could be an issue for those using both the iOS and Android applications.

**Comment by aquilent-dgemoets** [comment]
This selection was added prior to release of the iOS update that added Report PDF.  In the next beta, this will be changed to match the iOS version.

**Comment by jfc3-dol** [comment]
Thanks, for correcting this issue and I will close it.
