### ISSUE TITLE
Usability - Individual Country Screen - Country Detail Text Length Differs between iOS and Android

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#11]
\Why does the Android application show more the country write-up text than the iPad? They both show five lines of text but it much more on the Galaxy Tab S.

**Comment by aquilent-dgemoets** [comment]
As discussed in #1, iOS tablets simply scale phone apps to tablet size, whereas Android attempts to resize individual elements for larger screens, including tablets.  The effect is that Android is using the extra space to fit more text instead of just scaling up text size.

**Comment by jfc3-dol** [comment]
After being concerned that the text and images (flags, etc.) of the new ILAB 'Sweat & Toil' Android application would be too small after seeing it on the 'Galaxy Tab S' tablet. On Friday, November 20, 2015, I looked at an 'LG Tribute 2' phone and the text looked fine. 

Because of these findings I'm closing this and other related issues.
