### ISSUE TITLE
Usability - Suggested Actions Screen - Policy Text Differs between iOS and Android

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#12]
Why is the section text say “Policies” in Android application and “Government Policies” in the iPad version? Doing this could be an issue for those using both the iOS and Android applications

**Comment by aquilent-dgemoets** [comment]
Good catch-- we'll change the label to match the iOS version.

**Comment by jfc3-dol** [comment]
Thanks, for correcting this issue and I will close it.
