### ISSUE TITLE
Usability - Suggested Actions Screen - Country Name Missing

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#13]
Why is the country name missing from the Android version, but there for the iOS version of the application?

**Comment by aquilent-dgemoets** [comment]
See discussion for #3.

**Comment by jfc3-dol** [comment]
Okay, this could be confusing for those using iOS at work and then Android at home or vice versa that they don't have the same information going back to the previous screen. 

Closing issue.
