### ISSUE TITLE
Usability -  Information Goods Screen - Missing Navigation Text on Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#17]
Why does ‘Goods’ text appear next to the item type in the navigation on the individual goods screen for the iOS version, but not on Android version?

**Comment by aquilent-dgemoets** [comment]
See discussion for #3.

**Comment by jfc3-dol** [comment]
Okay, this could be confusing for those using iOS at work and then Android at home or vice versa that they don't have the same information going back to the previous screen. 

Closing issue.
