### ISSUE TITLE
Usability -  Information Goods Screen - Missing Country Navigation Text on Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#18]
When I go to an individual country from the goods screen, it does not tell me what the previous screen I came from.

**Comment by aquilent-dgemoets** [comment]
See discussion for #3.

**Comment by jfc3-dol** [comment]
Okay, this could be confusing for those using iOS at work and then Android at home or vice versa that they don't have the same information going back to the previous screen. 

Closing issue.
