### ISSUE TITLE
Usability -  Information Screens - Previous Screen Navigation

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#23]
When leaving the different information screens the application goes back to the main screen and I have to activate the ‘More Information” sections options again. Why not make a separate screen like there is on the iOS application to make it easier to use if a person is attempting to look at all this content?

**Comment by aquilent-dgemoets** [comment]
See discussion for #4.

**Comment by jfc3-dol** [comment]
Okay, this could be confusing for those using iOS at work and then Android at home or vice versa that they don't have the same information going back to the previous screen.

**Comment by aquilent-dgemoets** [comment]
I suspect that someone who uses both iOS and Android would be all too familiar with the differences between iOS and Android standard user interfaces, and understand why the option menu is used on the Android version of Sweat & Toil, but handled as a separate screen on the iOS version.

**Comment by jfc3-dol** [comment]
Okay, but similar to using a PC at work and a Mac at home you know there are differences between them, but it doesn't me it takes longer to use because they are different.

**Comment by jfc3-dol** [comment]
The usability issues of having to go back to open the information list and then the sections under it each time is not a great experience especially if you are using TalkBack.

**Comment by jfc3-dol** [comment]
By creating a "More info" page, the application has somewhere to go back to the main screen, and the user doesn't have to keep opening the "More info" drop down and chose and an item each time. Now They can go through the entire list if they want before heading back to the main screen.

Closing issue.
