### ISSUE TITLE
Accessibility - About this App Screen - Improper Un-Ordered List

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#25]
While reading this screen TalkBack reads the text of the first item of the bulleted list then the number and finally the text again. Never once mentioning it is a bulleted list.

**Comment by aquilent-dgemoets** [comment]
Much to our surprise, this appears to be how TalkBack currently reads ordered lists in standard Android WebViews.  We use the same HTML as the iOS version and put it in the standard Android WebView UI element.

**Comment by jfc3-dol** [comment]
I got the same thing happening with TalkBack on the OSHA Heat Index for an un-ordered list.

**Comment by aquilent-dgemoets** [comment]
Yep, it's just how TalkBack works at the moment.  Maybe they'll fix it in a future version of TalkBack.

**Comment by jfc3-dol** [comment]
The issues seems to have been corrected on this version of the application for the "About this App" screen at least.

So I'm closing the issue.
