### ISSUE TITLE
Usability -  Information Screens - Previous Screen Navigation

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#3]
Why when going to “Introduction” and other screens do I have to tap the ‘left arrow’ and not the ‘left arrow and the text’ at the top of the page to return to the previous page?

**Comment by aquilent-dgemoets** [comment]
In Android, the back arrow does not include the label of the previous screen like it does in iOS.  The arrow will be familiar to Android users.  This also applies to Issues #13, #17, and #18.

**Comment by jfc3-dol** [comment]
Okay, this could be confusing for those using iOS at work and then Android at home or vice versa that they don't have the same information going back to the previous screen. 

Closing issue.
