### ISSUE TITLE
Usability -  Information Screens - Navigation

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#4]
Having to open the ‘Information list’ every time to get to another item is annoying from a usability perspective.

**Comment by aquilent-dgemoets** [comment]
The Android option menu is a standard user interface element and will be familiar to Android users.  ILAB prefers to keep it as it is rather than create a whole new screen.  This also applies to Issue #23.

**Comment by jfc3-dol** [comment]
It would be much easier from a usability standpoint for those wanting to look at all the different screens in the 'More information" section to have in one place and not have to click on the button every time they want to see one. Doing this is even more of a pain for those using TalkBack, since once they return from/close the last one they get sent to the top left of the screen and have to work their way back before choosing another screen.

**Comment by jfc3-dol** [comment]
The issue with having to open the ‘Information list’ every time is still valid usability issue.

**Comment by NJICF** [comment]
A separate 'More information" screen with all menu items in one page added.

**Comment by jfc3-dol** [comment]
Thanks, for adding the new screen but the links to the other screens doesn't tell us what they are such as a button or link.

TalkBack reads for example "About This App" text as "About Sweat and Toil double tap to active". TalkBack should read "About This App" same as the displayed text.

It's also has a bunch of light gray rectangles above certain section which is where the heading level two (h2) items should be.

**Comment by NJICF** [comment]
Corrected the content description to say exactly the menu text.
The menu is similar to the menu in ios. In ios the gray rectangle is used to group similar menu items. Should a title be added for each group as header instead of gray rectangle.

**Comment by jfc3-dol** [comment]
@NJICF,

If the gray rectangles  are to group certain content together then it should have a heading level two (h2).

**Comment by NJICF** [comment]
added content description to the gray bars so that it will be read as heading level two.

**Comment by jfc3-dol** [comment]
@NJICF,

If you are done making changes to the Sweat and Toil Android application I will have @giridhar create and place the udpates to our devices.

**Comment by NJICF** [comment]
@jfc3-dol,

Yes I am done making changes. Thanks.

**Comment by jfc3-dol** [comment]
@NJICF,

I tested with TalkBack, and it read the text for each of the gray rectangles. I was expecting to see them visually.

They were not read as heading level two (h2) items.

**Comment by jfc3-dol** [comment]
The content descriptions for the gray boxes are being read by TalkBack but are still not visually on screen for others to read.

**Comment by jfc3-dol** [comment]
The content descriptions for the gray boxes are still being read by TalkBack but are still not visible on screen for others to read.

**Comment by jfc3-dol** [comment]
TalkBack is reading the two gray boxes as "Reports" and "Office of Child Labor, Forced Labor, and Human Trafficking", but there is no text visible for all users to read. These should be made into headings with the text visible in the gray boxes.

Because if this I'm leaving the issue open.

**Comment by jfc3-dol** [comment]
@pbhatt17 

TalkBack is ready the two gray boxes on the "More Info" page as "space" instead of the "Reports" and "Office of Child Labor, Forced Labor, and Human Trafficking" as it was previously.

If there is no text in the gray boxes, wouldn't it be better to remove them altogether?

**Comment by jfc3-dol** [comment]
@pbhatt17 

TalkBack is no longer reading the gray boxes, so I'm going to close this issue.
