### ISSUE TITLE
Territory abbreviations not introduced in Criminal subtab

### ISSUE THREAD

**Issue by aquilent-dgemoets** [USDepartmentofLabor/Child-Labor-Android#55]
The Labor subtab of the Enforcement screen introduces territory abbreviations the first time they are used.  The Criminal subtab could or should do the same, but doesn't.  It could be argued that they were "introduced" in the Labor tab-- which is a required step to get to the Criminal tab, but they should probably be mentioned in the Criminal tab as well.

At present, this only impacts Bosnia and Herzegovina, as it's the only multi-territory country with territory-specific data of an abbreviated territory.

**Comment by aquilent-dgemoets** [comment]
This is fixed in the 9/15 release.  Please confirm then close the issue.

**Comment by jfc3-dol** [comment]
TalkBack read the three different territory abbreviations on both the "Labor" and "Criminal" tabs as expected.
