### ISSUE TITLE
Longer Country Assessments Levels Incorrect

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#57]
Updated countries screens contain assessments levels with an assessment level of "Minimal Advancement Advancement". They should only have one "Advancement" for the following counties:

Armenia
Bolivia
Dominican Republic
Georgia
Sierra Leone
Ukraine

Please check the full list in case I missing a country.

**Comment by aquilent-dgemoets** [comment]
This is an error in the RAPP file and applies to both iOS and Android.
All of the "long" advancement types, e.g., "Minimal Advancement– Efforts Made but Continued Law that Delayed Advancement" have an extra "Advancement" in the latest RAPP file.

**Comment by jfc3-dol** [comment]
I don't remember seeing them on iOS, since we had similar issue the first version we tested  many months ago so I was kind of looking for it to possibly happen again. Will double check on one of our iOS devices now and report back.

**Comment by jfc3-dol** [comment]
Checked on our iPAd and none of the countries listed above have the word "Advancement" repeated twice in a row if that makes sense.

**Comment by aquilent-dgemoets** [comment]
It makes sense-- I think the double Advancement error was re-introduced in a later RAPP update.  For instance, the iOS beta that was released to GitHub yesterday will show the error, because it was in the latest RAPP file and not manually fixed in the file.

We need to ensure it gets fixed in ILAB's master version so that we don't have to remember to fix it every time locally.

**Comment by jfc3-dol** [comment]
we haven't put the newest version for iOS on our devices because we haven't gotten an e-mail from anyone or at least I haven't heard about it.

**Comment by aquilent-dgemoets** [comment]
Understood...it was released to GitHub yesterday but needs to be released via TestFlight.

By the way, ILAB has now fixed the double-Advancement issue in the master RAPP file.

**Comment by aquilent-dgemoets** [comment]
This is fixed in the 9/15 release.  Please confirm then close the issue.

**Comment by jfc3-dol** [comment]
Looked at list of countries above and all of them are now correct. So I will close this issue.
