### ISSUE TITLE
Missing Country Flags

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#58]
The following two countries are missing flags on the different country tabs:

West Bank & Gaza Strip
Western Sahara

**Comment by jfc3-dol** [comment]
The iOS application has the Western Sahara flag but not the West Bank & Gaza Strip one.

**Comment by aquilent-dgemoets** [comment]
I believe this is intended.  We will verify with ILAB.

**Comment by aquilent-dgemoets** [comment]
I've verified with ILAB that this is working as intended:  there should be no flags for Western Sahara and West Bank & Gaza Strip.

Related, there should be no country maps for:
•         Anguilla
•         British Virgin Islands
•         Christmas Island
•         Cocos (Keeling) Islands
•         Cook Islands
•         Falkland Islands (Islas Malvinas)
•         Montserrat
•         Niue
•         Norfolk Island
•         Saint Helena, Ascension, and Tristan
•         Tokelau
•         Western Sahara; and
•         West Bank & Gaza Strip.

I think we can close this issue.

**Comment by jfc3-dol** [comment]
Okay, with me if that is the way it is meant to be for both iOS and Android. Wanted to point it out in case they were supposed to be.

**Comment by aquilent-dgemoets** [comment]
Understood.  Also see Issue #9 .  I think all of these issues should be closed in GitHub, but I don't know OPA's policies for closing issues.

**Comment by jfc3-dol** [comment]
Okay, so I'm closing this issue.
