### ISSUE TITLE
Recommendation - TalkBack Reads "No." Incorrectly as "No" Instead of "Number"

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#59]
The Enforcement screen has the word "No." which VoiceOver reads as "No" when it is meant to be a number such as "number of people" instead of "no of people". Having it this way can be confusing to screen reader user.

**Comment by aquilent-dgemoets** [comment]
As of the 9/15 release, this should be in sync with the way these are handled in iOS.  See https://github.com/USDepartmentofLabor/Child-Labor/issues/57 .

**Comment by jfc3-dol** [comment]
TalkBack is now reading "No." as number so I will close this issue.
