### ISSUE TITLE
Accessibility - Main Country List Screen - Poor Color Contrast

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#6]
Need more color contrast for the way countries are broken up.

**Comment by aquilent-dgemoets** [comment]
See discussion for #2.

**Comment by jfc3-dol** [comment]
It doesn't matter if these are standard Android elements if the color contrast is poor it makes it difficult for people with visual issues to read the text, which is what you want people to do and it only is worse if a person is viewing information on phone or tablet is bright sunlight.
