### ISSUE TITLE
Accessibility - Symbol Not read by VoiceOver

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#60]
While reading the Cameroon "Legal Standards" screen VoiceOver never read the ‡ symbol on the page near the "YES" in the footnotes. Please check that it also reads it on other places in the page too.

**Comment by aquilent-dgemoets** [comment]
As of the 9/15 release, this should be addressed the same way it is handled in iOS:  it says the footer text after the value-- it doesn't need to say the symbol.  On Android, it also doesn't say the footer (which is desired behavior because the footer is redundant).

**Comment by jfc3-dol** [comment]
We like how TalkBack is now reading the text for the symbol and not the stuff in the footer, but the footer needs to be there for sighted people. Closing issue.
