### ISSUE TITLE
Functional - Goods Search Not in Alphabetical Order

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#61]
The Goods "Search" feature doesn't currently work properly for multi-word goods but the search results are not in alphabetical order for goods. If you enter "Silk" the list says Silk Fabric, Silk Thread, and Silk Cocoons. "Silk Cocoons" should be the first item in the list.

**Comment by aquilent-dgemoets** [comment]
This is fixed in the 9/15 release.  Please confirm, then close the issue.

**Comment by jfc3-dol** [comment]
The three "Silk" items are now sorted in the proper order so I am closing this issue.
