### ISSUE TITLE
Accessibility - TalkBack Not Reading Properly

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#62]
While reading with TalkBack (screen reader), I noticed if I tried to read from the top of the page on most if not all page it would only read the page name. If I were to tap on text on the screen and then have TalkBack read from the top of the screen, it would.

Not sure if this is an issue with our older tablet and most likely older version of TalkBack or an issue. Is there someone that can test this or someone's phone/tablet I can use to test this?

If you make an "L" shape on the screen a list of ways to read shows up and the first one is "Read from Top" which isn't working at first for me.

**Comment by aquilent-dgemoets** [comment]
We were unable to reproduce this issue using a modern device:  a Note 7 running Android 6.0.1.  What is the Android version of the tablet where you saw this behavior?

**Comment by jfc3-dol** [comment]
We are using a Galaxy Tab S model - SM-T700 with Android version 5.0.2. 

I'm not sure what version of TalkBack we are using.

As I stated, it might be our older device and older software version that is causing the issue. So if it works with your newer one I'm okay with that, unless someone else with older devices or software complains.

**Comment by jfc3-dol** [comment]
Now the application seems to read from the top to the bottom of the screen for countries once you start TalkBack reading the entire screen.

So closing the issue.
