### ISSUE TITLE
Legal Standards - Message Needs More Space It's Right Up Against Header Section

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#64]
While doing a quick review of the Android Sweat and Toil application before I start accessibility testing I noticed the Legal Standards screen has a "Meets International Standards *" message that needs more space it is right up against header section.

See attached screenshot.

![android - sweat and toil - legal standards - message needs more space it is right up against header section](https://user-images.githubusercontent.com/10423487/30345353-c8af6c36-97d2-11e7-9758-e163917157fc.png)

**Comment by carolynhuang** [comment]
This issue no longer exists. Additional white space was added.  
![screenshot_20171020-184859](https://user-images.githubusercontent.com/18356863/31844570-8e1cb282-b5c7-11e7-8a3a-415c1745f718.png)

**Comment by jfc3-dol** [comment]
Closing issue since it has been fixed.
