### ISSUE TITLE
About This App - Remove Rubik's Cube Link

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#69]
While double checking the remaining open issues, I noticed the "Methodology" screen had the heading level two (h2) text fixed and was working correctly with TalkBack. So I then checked the "About This App" screen too. 

When I got the bottom of the screen I noticed in the last sentence "easily" was spelled wrong as "esily". Upon further reading of the final paragraph, I saw the text is about Rubik's Cube and has a link.

@giridhar and I looked at the code, and the link was added with this last push of code.

Please remove it and double check there is no other code similar to on other screens. It seems extremely odd to add that in. 

Here is the link to the iOS "About This App" screen - https://github.com/USDepartmentofLabor/Child-Labor-Android/blob/2017-changes/app/src/main/assets/www/aboutthisapp.html

Here is the link to the commit of the code - https://github.com/USDepartmentofLabor/Child-Labor-Android/commit/16fae1e4f65563b0854c933e4f5bd98a5d3fec4b#diff-ea75a60f8f58a5b0831485f790b566c7

Plus, the link goes to a weirdly spelled version of Rubik's ( ruwix ).

**Comment by NJICF** [comment]
Removed the last sentence.

**Comment by jfc3-dol** [comment]
@NJICF,

Thanks, for making the update.

Has the change been merged so it can be pulled and recompiled?

Are there any other odd pieces of code you found?

I will check that it is removed once I have it on my devices and then close the issue.

**Comment by NJICF** [comment]
Yes. It is recompiled and the apk has been checked in.

**Comment by jfc3-dol** [comment]
@NJICF,

Thanks. for removing the unnecessary link and text.

Closing issue.
