### ISSUE TITLE
Android - Can't View PDF's on Device

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#72]
When attempting to open the "Child Labor Report". "Child and Forced Labor List of Goods", "Forced Child Labor List of Products" and "An Intro to OCFT" PDFs I get the following error message: 

Cannot display PDF (FILE NAME GOES HERE cannot be opened).

Please see the attached screenshot as an example.

![complychain - more info - cannot display pdfs](https://user-images.githubusercontent.com/10423487/44367831-e2b37580-a49e-11e8-846f-f16a1ff380a0.png)

**Comment by carolynhuang** [comment]
All PDFs in the Info section have been removed because we are in the process of finalizing the new reports. This will be addressed by launch in mid-Sept.

**Comment by jfc3-dol** [comment]
Thanks, for the update.

I will leave this issue open so I remember to check that the PDFs are there when the final version comes out.

**Comment by jfc3-dol** [comment]
@carolynhuang 

The PDF's are now opening as expected but the wording for the "Secreatry's Forward" link has been changed to only be "Forward". Any reason this changed?

If that is okay we can close this issue then.

**Comment by carolynhuang** [comment]
@jfc3-dol This was intentional - the reason is that we are also including our Deputy Under Secretary's foreword, so it is no longer just the Secretary's introduction.

**Comment by jfc3-dol** [comment]
Okay, I thought I would bring it up in case it was a mistake.

Closing issue.

**Comment by jfc3-dol** [comment]
Okay, I thought I would bring it up in case it was a mistake.

Closing issue.
