### ISSUE TITLE
Functional - The "An Infro to OCFT" is Missing from "More Info" Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#74]
Not sure which application is corrected but the "An Intro to OCFT" link is missing in the Android application but is there for the iOS version.

Is there any reason it is in one and not the other?

Will create a similar issue for the iOS version so we can remove or add it to the other depending on what's supposed to happen.

**Comment by carolynhuang** [comment]
@jfc3-dol We asked that it be removed from both apps, since this PDF is being updated but will not be available by the time of the launch of this app. It should not exist in the iOS app.

**Comment by jfc3-dol** [comment]
Thanks, for the update. I figured one of them was incorrect and the other was correct. 

Closing this issues and leaving the iOS one open until it is removed from the application.
