### ISSUE TITLE
Functional - Individual Country - Products Not in Alphabetic Order

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#78]
While testing that TalkBack is reading all the items in the list instead ofonly the four or five that show on the screen I noticed at the end that the list is now not in alphabetic order.

Is there any reason why in the India screen Cotton" is at the end after "Thread/Yarn" instead towards the beginning?

Please see the attached screenshot.

![sweat and toil - india - cotton not in alphabetic order](https://user-images.githubusercontent.com/10423487/63106482-ea421900-bf50-11e9-912c-ae0a81955be4.jpg)

**Comment by clguidi** [comment]
ZTI please address this

**Comment by clguidi** [comment]
John, this has been addressed. Please download the latest build and close this when possible.

**Comment by jfc3-dol** [comment]
@clguidi,

Thanks for fixing the issue and hopefully any other out of order goods were placed in alphabetic or in other countries. Because of this being corrected I'm going to close the issue.

Please see the attached screenshots.

**Cotton in alphabetic order.**

![sweat and toil - india - cotton is now in alphabetic order](https://user-images.githubusercontent.com/10423487/65355689-7e427880-dbc0-11e9-8025-b14887d5ab76.png)

**Cotton not following thread/yarn.**

![sweat and toil - india - cotton is now in alphabetic order and not after thread yarn](https://user-images.githubusercontent.com/10423487/65355687-7e427880-dbc0-11e9-8dfb-66e47171567a.png)
