### ISSUE TITLE
Accessibility - Main Country List Screen - Small Flags and Text

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#8]
Country flags and text are small and difficult to read.

**Comment by aquilent-dgemoets** [comment]
If this was observed on a tablet, then please see Issue #1.  If this was observed on a phone, then Android default fonts were used, but we may be able to specify larger font sizes for larger phones, as time permits. This is currently at the top of our "if time permits" list.

**Comment by jfc3-dol** [comment]
After being concerned that the text and images (flags, etc.) of the new ILAB 'Sweat & Toil' Android application would be too small after seeing it on the 'Galaxy Tab S' tablet. On Friday, November 20, 2015, I looked at an 'LG Tribute 2' phone and the images looked fine. 

Because of these findings I'm closing this and other related issues.
