### ISSUE TITLE
Functioanl - More Info - The Forward has Photo of the Old Secrtary 

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#80]
The "Forward" link documents have a photo of the old Secretary and not sure if you want to remove it or not.

**Comment by clguidi** [comment]
Thank you John. This has been addressed, please download the latest build of the app and close this issue when possible.

**Comment by jfc3-dol** [comment]
@clguidi,

The Forward now shows an image of the Acting Secretary, so I'm going to close this issue.

Please see the attached screenshot.

![sweat and toil - Forward - now shows acting secretary](https://user-images.githubusercontent.com/10423487/65355199-628aa280-dbbf-11e9-8b3d-7d2a6f2df285.png)
