### ISSUE TITLE
Accessibility - On "Legal Standards" Screen TalkBack Not Reading Special Character Footnote

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#83]
While testing with TalkBack, we noticed on the "Legal Standards" screen TalkBack is not reading the special character (asterisk) or the character after the "18" for "Compulsory Education Age" for the "Dominican Republic" as a footnote which it did previously. The footnote is at the bottom of the page, and I think was being added to the specific line as an accessible label or something like that previously.

TalkBack is not reading the asterisk at all let alone as the text is represents in the footer.

Additionally, TalkBack is only reading the last "Yes" for the "Dominican Republic" screen and not any of the footnote information below it.

**Comment by jfc3-dol** [comment]
TalkBack now reads the footnote content at the end of the screen but does not the asterisk for the record and what it means. So I'm going to keep this issue open for now.

**Comment by harpreetsdev** [comment]
@jfc3-dol 
And this one too. We will make a note in the release documents with the Sweat and Toil release.

@pbhatt17 @Abychalil

**Comment by jfc3-dol** [comment]
@harpreetsdev @pbhatt17 @Abychalil

Once I get the build from the OPA Tech team, most likely early next week, I will test this again.

**Comment by jfc3-dol** [comment]
@pbhatt17 

TalkBack is still not reading the special characters (cross, railroad track,  in the "Legal Standards" pages I looked at randomly such as Afghanistan, Anguilla, Armenia, Azerbaijan, Bolivia, etc.

I'm going to gather a list of the other countries that still have special characters and don't work with TalkBack after checking the issues related to the two ILAB iOS applications or someone else can.

**Comment by jfc3-dol** [comment]
@pbhatt17 

On the listed above countrys' "Legal Standards" page, there are no special characters anymore. From the other list of countries I had started, there are no special characters anymore either.

So I'm going to close this issue.
