### ISSUE TITLE
Functional - Enforcement - For Brazil Why is There 56 after Answers

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#84]
While looking at the "Labor" tab on the Enforcement screen for Brazil, I notice "(56)" after almost every answer that had something after it but one which was 59. The "Criminal" tab had different numbers while on other screens those numbers related to children's ages or some other code that was defined at the bottom of the screen and there is nothing on this page. I guess that the application is displaying the number from the record and not converting it to other text or special characters that have given meaning.

Please see the attached screenshots to show what I'm talking about.

Labor tab

![sweat and toil - brazil - enhancement - why are there number like 56 in brackets of the labor tab](https://user-images.githubusercontent.com/10423487/63118042-0a7ed180-bf6b-11e9-89b7-3760fa58270b.jpg)

Criminal tab

![sweat and toil - brazil - enhancement - why are there number like 55 and 56 in brackets of the criminal tab](https://user-images.githubusercontent.com/10423487/63118146-487bf580-bf6b-11e9-9ed9-4237973d24b4.jpg)

**Comment by clguidi** [comment]
John, please download the latest test build and review this issue. It has been addressed. Please close this when you are able.

**Comment by jfc3-dol** [comment]
@clguidi,

I have the same issue on my tablet as before. I'm beginning to wonder if I have the latest version of the application on our tablet.

Is there any way you can manually install the update on our two devices tomorrow (Wednesday) so I can test?

**Comment by jfc3-dol** [comment]
@clguidi,

The latest version does not have the extra numbers for Brazil and a few other countries I randomly selected to check. So I'm going to close the issue.
