### ISSUE TITLE
Functional - Country - Report PDF Link is Showing 2017 PDF Instead of 2018 Content

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#85]
On the countries, I looked at randomly the "Report PDF" link is showing PDF content from 2017 instead of 2018, which is what I was expecting to see.

Please see the attached screenshot as an example.

![sweat and toil - android - Turkey - report pdf showing 2017 content instead of 2018 as expected](https://user-images.githubusercontent.com/10423487/63118605-351d5a00-bf6c-11e9-9466-44105706ec20.png)

**Comment by clguidi** [comment]
Thank you John, we cannot address this at the moment. We will come back to this.

**Comment by jfc3-dol** [comment]
@clguidi,

I assume once you get the final PDFs.

**Comment by clguidi** [comment]
John, we have now addressed. Please verify this using the latest test build and close this when you are able. Thank you.

**Comment by jfc3-dol** [comment]
@clguidi,

I have the same issue on my tablet as before. I'm beginning to wonder if I have the latest version of the application on our tablet.

Is there anyway you can manually install the update on our two devices tomorrow (Wednesday) so I can test?

**Comment by jfc3-dol** [comment]
@clguidi,

Thanks for updating the PDFs, so they now show 2018 content. I randomly looked at a few countries, and everything looked good. So I'm going to close the issue.
