### ISSUE TITLE
Functional - Check for Broken Links

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#86]
While testing the iOS version of the application, I noticed that there were a lot of ILAB website links that were either redirected to the new URL since moving to Drupal and other pages was not found either because they were deleted or the URL is incorrect now.

So please check all the links are correct. I can't test now because the wifi for my device keeps cutting out.

**Comment by clguidi** [comment]
Thank you John. We will correct this.

**Comment by clguidi** [comment]
John, could you please recheck this using the latest build of the app and close this as soon as you can? Thank you.

**Comment by jfc3-dol** [comment]
@clguidi,

The different country pages "Report PDF" link is pointing to the 2017 reports.

My old Samsung Tablet is not connecting to the internet, so I can't check the links that go to web pages at the moment. Our Samsung phone connects, but we were not able to download the application to that device.

**Comment by jfc3-dol** [comment]
@clguidi,

All the links I tested from the "More Info" screens worked as expect, so I'm going to close the issue.
