### ISSUE TITLE
Usability - Main Country List Screen - Missing Country Flags

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#9]
Why are the flags for “Montserrat”, “West Bank and the Gaza Strip”, and “Western Sahara”, missing before the countries name?

**Comment by aquilent-dgemoets** [comment]
The flag for Montserrat will be fixed in the next beta-- thank you.  There were no flags provided for “West Bank and the Gaza Strip”, and “Western Sahara," just like in iOS.

**Comment by jfc3-dol** [comment]
Okay, ILAB couldn't send you the flags for the missing two countries of “West Bank and the Gaza Strip” and “Western Sahara"?

**Comment by aquilent-dgemoets** [comment]
That's correct.  My understanding is that the US Government does not recognize these countries, or something to that effect.  Either way, this is working as intended and the same on iOS.

**Comment by jfc3-dol** [comment]
flags have not been updated in this version of the application.

**Comment by carolynhuang** [comment]
No flags will be added, since these are disputed territories which the USG does not recognize as sovereign countries. Please close out this issue.

**Comment by jfc3-dol** [comment]
@carolynhuang,

That's fine but I'm going to keep it open so we remember to check each year in case they become recognized countries.

**Comment by jfc3-dol** [comment]
If flags are not going to be added, I'm closing this issue.
